export interface MarketplaceProduct {
  id: number
  name: string
  article: string
  exactName: string
  category: string
  subcategory: string
  brand: string
  description: string
  country: string
  weightKg: number
  lengthCm: number
  widthCm: number
  heightCm: number
  color: string
  material: string
  model: string
  keywords: string[]
  photoUrls: string[]
  equipment: string
  warranty: string
  ageCategory: string
}

export const MARKETPLACE_PRODUCTS: MarketplaceProduct[] = [
  {
    id: 1,
    name: "Ноутбук Lenovo ThinkPad E14",
    article: "TS-NB-001",
    exactName: "Ноутбук Lenovo ThinkPad E14 Gen 5 21JNS0RK00",
    category: "Электроника",
    subcategory: "Ноутбуки",
    brand: "Lenovo",
    description: "Ноутбук для бизнеса с процессором Intel Core i5-1335U, 16 ГБ ОЗУ, SSD 512 ГБ, экран 14\" IPS FHD",
    country: "Китай",
    weightKg: 1.6,
    lengthCm: 32.4,
    widthCm: 22.6,
    heightCm: 1.8,
    color: "Чёрный",
    material: "Пластик / Алюминий",
    model: "21JNS0RK00",
    keywords: ["ноутбук", "lenovo", "thinkpad", "бизнес", "i5", "16gb"],
    photoUrls: ["https://img.techsupply.ru/nb-001-1.jpg", "https://img.techsupply.ru/nb-001-2.jpg"],
    equipment: "Ноутбук, зарядное устройство 65Вт, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 2,
    name: "Монитор Dell S2722QC",
    article: "TS-MN-002",
    exactName: "Монитор Dell S2722QC 27\" 4K USB-C",
    category: "Электроника",
    subcategory: "Мониторы",
    brand: "Dell",
    description: "Монитор 27\" IPS 4K UHD с USB-C до 65Вт, HDR400, 99% sRGB",
    country: "Китай",
    weightKg: 5.5,
    lengthCm: 61.1,
    widthCm: 36.9,
    heightCm: 18.4,
    color: "Серебристый / Чёрный",
    material: "Пластик / Металл",
    model: "S2722QC",
    keywords: ["монитор", "dell", "4k", "usb-c", "27дюймов"],
    photoUrls: ["https://img.techsupply.ru/mn-002-1.jpg", "https://img.techsupply.ru/mn-002-2.jpg"],
    equipment: "Монитор, кабель USB-C, кабель HDMI, подставка, документация",
    warranty: "24 месяца",
    ageCategory: "6+",
  },
  {
    id: 3,
    name: "Клавиатура Logitech MX Keys S",
    article: "TS-KB-003",
    exactName: "Клавиатура Logitech MX Keys S Wireless",
    category: "Электроника",
    subcategory: "Периферия",
    brand: "Logitech",
    description: "Беспроводная клавиатура с подсветкой, Bluetooth + USB-ресивер,剪刀式 механизм",
    country: "Китай",
    weightKg: 0.81,
    lengthCm: 43.3,
    widthCm: 13.2,
    heightCm: 2.1,
    color: "Тёмно-серый",
    material: "Пластик / Металл",
    model: "920-011223",
    keywords: ["клавиатура", "logitech", "беспроводная", "подсветка", "mx-keys"],
    photoUrls: ["https://img.techsupply.ru/kb-003-1.jpg"],
    equipment: "Клавиатура, USB-ресивер, кабель USB-C, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 4,
    name: "Мышь Logitech MX Master 3S",
    article: "TS-MS-004",
    exactName: "Мышь Logitech MX Master 3S Wireless",
    category: "Электроника",
    subcategory: "Периферия",
    brand: "Logitech",
    description: "Беспроводная мышь с электромагнитным колесом, 8000 DPI, Bluetooth + USB",
    country: "Китай",
    weightKg: 0.14,
    lengthCm: 12.6,
    widthCm: 8.4,
    heightCm: 4.7,
    color: "Графитовый",
    material: "Пластик / Резина",
    model: "910-006556",
    keywords: ["мышь", "logitech", "беспроводная", "ergonomic", "mx-master"],
    photoUrls: ["https://img.techsupply.ru/ms-004-1.jpg"],
    equipment: "Мышь, USB-ресивер, кабель USB-C, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 5,
    name: "Наушники Jabra Evolve2 85",
    article: "TS-HP-005",
    exactName: "Наушники Jabra Evolve2 85 UC Wireless",
    category: "Электроника",
    subcategory: "Периферия",
    brand: "Jabra",
    description: "Накладные наушники с активным шумоподавлением, Bluetooth 5.1, 37ч автономность",
    country: "Китай",
    weightKg: 0.29,
    lengthCm: 20.5,
    widthCm: 18.4,
    heightCm: 7.2,
    color: "Чёрный",
    material: "Пластик / Кожзаменитель",
    model: "23985-889-889",
    keywords: ["наушники", "jabra", "anc", "беспроводные", "офис"],
    photoUrls: ["https://img.techsupply.ru/hp-005-1.jpg"],
    equipment: "Наушники, база для зарядки, кабель USB-C, чехол, документация",
    warranty: "24 месяца",
    ageCategory: "6+",
  },
  {
    id: 6,
    name: "Веб-камера Logitech Brio 4K",
    article: "TS-WC-006",
    exactName: "Веб-камера Logitech Brio 4K Stream Edition",
    category: "Электроника",
    subcategory: "Периферия",
    brand: "Logitech",
    description: "4K HDR веб-камера с автокадрированием, USB-C, Windows Hello",
    country: "Китай",
    weightKg: 0.11,
    lengthCm: 10.2,
    widthCm: 2.9,
    heightCm: 3.7,
    color: "Чёрный",
    material: "Пластик / Металл",
    model: "960-001291",
    keywords: ["веб-камера", "4k", "logitech", "hdr", "stream"],
    photoUrls: ["https://img.techsupply.ru/wc-006-1.jpg"],
    equipment: "Камера, кабель USB-C, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 7,
    name: "МФУ HP LaserJet Pro MFP 4101fdw",
    article: "TS-PR-007",
    exactName: "МФУ HP LaserJet Pro MFP 4101fdw",
    category: "Офисное оборудование",
    subcategory: "Принтеры",
    brand: "HP",
    description: "Лазерное МФУ: принтер/сканер/копир/факс, A4, 40 стр/мин, Wi-Fi, дуплекс",
    country: "Китай",
    weightKg: 14.6,
    lengthCm: 42.1,
    widthCm: 39.9,
    heightCm: 34.2,
    color: "Белый",
    material: "Пластик",
    model: "4101fdw",
    keywords: ["мфу", "hp", "лазерный", "принтер", "wifi", "дуплекс"],
    photoUrls: ["https://img.techsupply.ru/pr-007-1.jpg", "https://img.techsupply.ru/pr-007-2.jpg"],
    equipment: "МФУ, картридж стартовый, кабель питания, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 8,
    name: "ИБП APC Smart-UPS 1500VA",
    article: "TS-UPS-008",
    exactName: "ИБП APC Smart-UPS SRT 1500VA LCD 230V",
    category: "Офисное оборудование",
    subcategory: "ИБП",
    brand: "APC",
    description: "Источники бесперебойного питания 1500ВА/1350Вт, онлайн, LCD, SNMP",
    country: "Китай",
    weightKg: 23.5,
    lengthCm: 43.2,
    widthCm: 35.5,
    heightCm: 8.7,
    color: "Чёрный",
    material: "Металл / Пластик",
    model: "SRT5KXLI",
    keywords: ["ибп", "apc", "ups", "1500va", "online"],
    photoUrls: ["https://img.techsupply.ru/ups-008-1.jpg"],
    equipment: "ИБП, кабель питания, документация",
    warranty: "24 месяца",
    ageCategory: "6+",
  },
  {
    id: 9,
    name: "Проектор Epson EB-X51",
    article: "TS-PJ-009",
    exactName: "Проектор Epson EB-X51 3LCD XGA 3700 лм",
    category: "Офисное оборудование",
    subcategory: "Проекторы",
    brand: "Epson",
    description: "3LCD проектор, XGA 1024x768, 3700 лм, контраст 16000:1, HDMI",
    country: "Китай",
    weightKg: 2.5,
    lengthCm: 30.2,
    widthCm: 24.4,
    heightCm: 8.7,
    color: "Белый",
    material: "Пластик",
    model: "V11H951040",
    keywords: ["проектор", "epson", "3lcd", "xga", "офис"],
    photoUrls: ["https://img.techsupply.ru/pj-009-1.jpg"],
    equipment: "Проектор, кабель питания, кабель VGA, документация",
    warranty: "24 месяца",
    ageCategory: "6+",
  },
  {
    id: 10,
    name: "Роутер MikroTik hAP ax3",
    article: "TS-RTR-010",
    exactName: "Роутер MikroTik hAP ax3 C53UiG+5HPaxD2HPaxD",
    category: "Сетевое оборудование",
    subcategory: "Роутеры",
    brand: "MikroTik",
    description: "Wi-Fi 6 роутер, 2.4+5 ГГц, 4 порта 1G, USB, RouterOS 7",
    country: "Латвия",
    weightKg: 0.45,
    lengthCm: 17.2,
    widthCm: 13.4,
    heightCm: 3.5,
    color: "Белый",
    material: "Пластик",
    model: "C53UiG+5HPaxD2HPaxD",
    keywords: ["роутер", "mikrotik", "wifi6", "ax", "гигабитный"],
    photoUrls: ["https://img.techsupply.ru/rtr-010-1.jpg"],
    equipment: "Роутер, блок питания, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 11,
    name: "ИП-камера Hikvision DS-2CD2143G2-I",
    article: "TS-CAM-011",
    exactName: "ИП-камера Hikvision DS-2CD2143G2-I 4мм",
    category: "Сетевое оборудование",
    subcategory: "Камеры",
    brand: "Hikvision",
    description: "IP-камера 4Мп, купольная, ИК до 30м, AcuSense, WDR 120дБ, PoE",
    country: "Китай",
    weightKg: 0.55,
    lengthCm: 11.2,
    widthCm: 11.2,
    heightCm: 7.8,
    color: "Белый",
    material: "Металл / Пластик",
    model: "DS-2CD2143G2-I(4mm)",
    keywords: ["камера", "hikvision", "ip", "купол", "4мп", "poe"],
    photoUrls: ["https://img.techsupply.ru/cam-011-1.jpg"],
    equipment: "Камера, кронштейн, документация",
    warranty: "24 месяца",
    ageCategory: "6+",
  },
  {
    id: 12,
    name: "Кресло Herman Miller Aeron",
    article: "TS-CHR-012",
    exactName: "Кресло Herman Miller Aeron Remastered Size B",
    category: "Мебель",
    subcategory: "Кресла",
    brand: "Herman Miller",
    description: "Эргономичное офисное кресло, сетка, регулировка поясницы, подлокотники 4D",
    country: "США",
    weightKg: 18.0,
    lengthCm: 69.0,
    widthCm: 69.0,
    heightCm: 101.0,
    color: "Графитовый",
    material: "Сетка / Алюминий / Пластик",
    model: "Aeron Remastered B",
    keywords: ["кресло", "herman-miller", "aeron", "эргономичное", "офис"],
    photoUrls: ["https://img.techsupply.ru/chr-012-1.jpg", "https://img.techsupply.ru/chr-012-2.jpg"],
    equipment: "Кресло, инструкция по сборке",
    warranty: "12 месяцев",
    ageCategory: "12+",
  },
  {
    id: 13,
    name: "Стойка телекоммуникационная 19\"",
    article: "TS-RCK-013",
    exactName: "Стойка 19\" 22U напольная Rittal",
    category: "Мебель",
    subcategory: "Стойки",
    brand: "Rittal",
    description: "Напольная телекоммуникационная стойка 22U, 600x800, стекло-дверь, вентиляция",
    country: "Германия",
    weightKg: 45.0,
    lengthCm: 60.0,
    widthCm: 80.0,
    heightCm: 120.0,
    color: "Чёрный / Серый",
    material: "Сталь",
    model: "AE1060.500",
    keywords: ["стойка", "19дюймов", "серверная", "22u", "rittal"],
    photoUrls: ["https://img.techsupply.ru/rck-013-1.jpg"],
    equipment: "Стойка, крепёж, документация",
    warranty: "24 месяца",
    ageCategory: "12+",
  },
  {
    id: 14,
    name: "Принтер Canon PIXMA G3410",
    article: "TS-PR-014",
    exactName: "Принтер Canon PIXMA G3410 струйный",
    category: "Офисное оборудование",
    subcategory: "Принтеры",
    brand: "Canon",
    description: "Струйный принтер с СНПЧ, A4, Wi-Fi, сканер, копир, 5 стр/мин ч/б",
    country: "Китай",
    weightKg: 6.5,
    lengthCm: 44.5,
    widthCm: 33.0,
    heightCm: 16.3,
    color: "Чёрный",
    material: "Пластик",
    model: "G3410",
    keywords: ["принтер", "canon", "струйный", "снпч", "wifi"],
    photoUrls: ["https://img.techsupply.ru/pr-014-1.jpg"],
    equipment: "Принтер, чернила, кабель питания, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 15,
    name: "Микрофон Rode NT-USB+",
    article: "TS-MIC-015",
    exactName: "Микрофон Rode NT-USB+ Studio",
    category: "Электроника",
    subcategory: "Периферия",
    brand: "Rode",
    description: "Студийный USB-микрофон, конденсаторный, 24бит/48кГц, поп-фильтр в комплекте",
    country: "Австралия",
    weightKg: 0.53,
    lengthCm: 17.5,
    widthCm: 6.3,
    heightCm: 16.2,
    color: "Чёрный",
    material: "Металл",
    model: "NT-USB+",
    keywords: ["микрофон", "rode", "usb", "студийный", "конденсаторный"],
    photoUrls: ["https://img.techsupply.ru/mic-015-1.jpg"],
    equipment: "Микрофон, подставка, поп-фильтр, кабель USB, документация",
    warranty: "24 месяца",
    ageCategory: "6+",
  },
  {
    id: 16,
    name: "Акустика JBL Professional 305P MkII",
    article: "TS-SPK-016",
    exactName: "Акустика JBL Professional 305P MkII",
    category: "Электроника",
    subcategory: "Периферия",
    brand: "JBL",
    description: "Студийные мониторы 5\", пара, 50Вт, 41Гц-24кГц, XLR/TRS",
    country: "Китай",
    weightKg: 5.3,
    lengthCm: 16.6,
    widthCm: 20.2,
    heightCm: 23.3,
    color: "Чёрный",
    material: "МДФ / Пластик",
    model: "305P MkII",
    keywords: ["акустика", "jbl", "мониторы", "студийные", "5дюймов"],
    photoUrls: ["https://img.techsupply.ru/spk-016-1.jpg"],
    equipment: "2 монитора, кабели питания, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 17,
    name: "Кабель HDMI 2.1 3м",
    article: "TS-CBL-017",
    exactName: "Кабель HDMI 2.1 Ultra High Speed 3м",
    category: "Электроника",
    subcategory: "Периферия",
    brand: "Cable Matters",
    description: "HDMI 2.1 48Gbps, 8K@60Hz/4K@120Hz, eARC, HDR, 3м",
    country: "Китай",
    weightKg: 0.15,
    lengthCm: 300.0,
    widthCm: 1.2,
    heightCm: 0.8,
    color: "Чёрный",
    material: "Медь / ПВХ",
    model: "201028-BLK-3M",
    keywords: ["кабель", "hdmi", "2.1", "8k", "4k120"],
    photoUrls: ["https://img.techsupply.ru/cbl-017-1.jpg"],
    equipment: "Кабель HDMI, упаковка",
    warranty: "6 месяцев",
    ageCategory: "6+",
  },
  {
    id: 18,
    name: "Сумка для ноутбука Targus TSB882AP",
    article: "TS-BAG-018",
    exactName: "Сумка Targus CityGear 15.6\" TSB882AP",
    category: "Электроника",
    subcategory: "Периферия",
    brand: "Targus",
    description: "Рюкзак для ноутбука 15.6\", отсек для планшета, водонепроницаемая ткань",
    country: "Китай",
    weightKg: 0.9,
    lengthCm: 32.0,
    widthCm: 20.0,
    heightCm: 47.0,
    color: "Чёрный",
    material: "Полиэстер",
    model: "TSB882AP",
    keywords: ["сумка", "рюкзак", "ноутбук", "targus", "15.6"],
    photoUrls: ["https://img.techsupply.ru/bag-018-1.jpg"],
    equipment: "Рюкзак, документация",
    warranty: "24 месяца",
    ageCategory: "6+",
  },
  {
    id: 19,
    name: "Зарядное устройство Anker 737",
    article: "TS-CHG-019",
    exactName: "Зарядное устройство Anker 737 PowerBank 24000мАч",
    category: "Электроника",
    subcategory: "Периферия",
    brand: "Anker",
    description: "Портативный аккумулятор 24000мАч, 140Вт USB-C PD, 2xUSB-C + USB-A",
    country: "Китай",
    weightKg: 0.63,
    lengthCm: 15.5,
    widthCm: 7.5,
    heightCm: 5.4,
    color: "Чёрный",
    material: "Пластик",
    model: "A1289",
    keywords: ["зарядка", "powerbank", "anker", "140w", "usb-c"],
    photoUrls: ["https://img.techsupply.ru/chg-019-1.jpg"],
    equipment: "PowerBank, кабель USB-C, документация",
    warranty: "18 месяцев",
    ageCategory: "6+",
  },
  {
    id: 20,
    name: "USB-хаб Satechi USB-C Multiport",
    article: "TS-HUB-020",
    exactName: "USB-хаб Satechi USB-C Multiport Adapter V3",
    category: "Электроника",
    subcategory: "Периферия",
    brand: "Satechi",
    description: "USB-C хаб: HDMI 4K60, USB-A 3.0 x2, SD/microSD, PD 100Вт passthrough",
    country: "Китай",
    weightKg: 0.09,
    lengthCm: 11.5,
    widthCm: 4.5,
    heightCm: 1.5,
    color: "Серебристый",
    material: "Алюминий",
    model: "ST-UC3MA",
    keywords: ["хаб", "usb-c", "satechi", "hdmi", "multiport"],
    photoUrls: ["https://img.techsupply.ru/hub-020-1.jpg"],
    equipment: "Хаб, чехол, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 21,
    name: "Моноблок Apple iMac 24\" M3",
    article: "TS-AIO-021",
    exactName: "Моноблок Apple iMac 24\" M3 8/256",
    category: "Электроника",
    subcategory: "Мониторы",
    brand: "Apple",
    description: "Моноблок 24\" 4.5K Retina, Apple M3 8-ядер, 8 ГБ, SSD 256 ГБ, синий",
    country: "Китай",
    weightKg: 4.48,
    lengthCm: 54.7,
    widthCm: 36.9,
    heightCm: 14.7,
    color: "Синий",
    material: "Алюминий / Стекло",
    model: "MYW43LL/A",
    keywords: ["моноблок", "imac", "apple", "m3", "24дюйма"],
    photoUrls: ["https://img.techsupply.ru/aio-021-1.jpg", "https://img.techsupply.ru/aio-021-2.jpg"],
    equipment: "iMac, клавиатура Magic, мышь Magic Mouse, кабель питания, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 22,
    name: "Плоттер HP DesignJet T650",
    article: "TS-PLT-022",
    exactName: "Плоттер HP DesignJet T650 36\" принтер",
    category: "Офисное оборудование",
    subcategory: "Принтеры",
    brand: "HP",
    description: "Широкоформатный принтер A0, 36\", 80 стр/ч, Wi-Fi, USB, Auto-Nest",
    country: "Китай",
    weightKg: 55.0,
    lengthCm: 130.0,
    widthCm: 54.0,
    heightCm: 108.0,
    color: "Серый",
    material: "Металл / Пластик",
    model: "5PA10A",
    keywords: ["плоттер", "hp", "designjet", "a0", "широкоформатный"],
    photoUrls: ["https://img.techsupply.ru/plt-022-1.jpg"],
    equipment: "Плоттер, картриджи, держатель рулона, документация",
    warranty: "12 месяцев",
    ageCategory: "12+",
  },
  {
    id: 23,
    name: "Уничтожитель документов Fellowes 125Ci",
    article: "TS-SHD-023",
    exactName: "Уничтожитель документов Fellowes Powershred 125Ci",
    category: "Офисное оборудование",
    subcategory: "Принтеры",
    brand: "Fellowes",
    description: "Шредер кросс-кат, 18 листов, автоподача 60 листов, CD/карты, 30л корзина",
    country: "Китай",
    weightKg: 16.0,
    lengthCm: 40.6,
    widthCm: 33.5,
    heightCm: 57.7,
    color: "Чёрный",
    material: "Пластик / Металл",
    model: "4665201",
    keywords: ["шредер", "уничтожитель", "fellowes", "кросс-кат", "офис"],
    photoUrls: ["https://img.techsupply.ru/shd-023-1.jpg"],
    equipment: "Шредер, корзина, документация",
    warranty: "24 месяца",
    ageCategory: "12+",
  },
  {
    id: 24,
    name: "Детектор валют Cassida Advantage 75",
    article: "TS-DET-024",
    exactName: "Детектор валют Cassida Advantage 75 UV/MG",
    category: "Офисное оборудование",
    subcategory: "Принтеры",
    brand: "Cassida",
    description: "Мультивалютный детектор UV/MG/IR, автоматический, дисплей LCD",
    country: "Китай",
    weightKg: 1.1,
    lengthCm: 19.5,
    widthCm: 15.5,
    heightCm: 8.5,
    color: "Белый",
    material: "Пластик",
    model: "Advantage 75",
    keywords: ["детектор", "валюты", "cassida", "uv", "mg"],
    photoUrls: ["https://img.techsupply.ru/det-024-1.jpg"],
    equipment: "Детектор, кабель питания, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 25,
    name: "Сканер Fujitsu ScanSnap iX1600",
    article: "TS-SCN-025",
    exactName: "Сканер Fujitsu ScanSnap iX1600 Wireless",
    category: "Офисное оборудование",
    subcategory: "Принтеры",
    brand: "Fujitsu",
    description: "Документный сканер, A4, дуплекс, 40 стр/мин, Wi-Fi, USB 3.0, сенсильный LCD",
    country: "Китай",
    weightKg: 3.3,
    lengthCm: 29.2,
    widthCm: 16.2,
    heightCm: 16.0,
    color: "Белый / Тёмно-серый",
    material: "Пластик",
    model: "PA03770-B405",
    keywords: ["сканер", "fujitsu", "scansnap", "документный", "wifi"],
    photoUrls: ["https://img.techsupply.ru/scn-025-1.jpg"],
    equipment: "Сканер, кабель USB, кабель питания, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 26,
    name: "Док-станция CalDigit TS4",
    article: "TS-DOCK-026",
    exactName: "Док-станция CalDigit Thunderbolt Station 4",
    category: "Электроника",
    subcategory: "Периферия",
    brand: "CalDigit",
    description: "Thunderbolt 4 док: 18 портов, TB4 x3, USB-A 3.2 x5, SD, 2.5GbE, 98Вт PD",
    country: "Китай",
    weightKg: 0.94,
    lengthCm: 21.8,
    widthCm: 10.0,
    heightCm: 5.5,
    color: "Серебристый",
    material: "Алюминий",
    model: "TS4",
    keywords: ["док-станция", "caldigit", "thunderbolt", "ts4", "18портов"],
    photoUrls: ["https://img.techsupply.ru/dock-026-1.jpg"],
    equipment: "Док-станция, кабель TB4, блок питания, документация",
    warranty: "24 месяца",
    ageCategory: "6+",
  },
  {
    id: 27,
    name: "Сервер Dell PowerEdge R740",
    article: "TS-SRV-027",
    exactName: "Сервер Dell PowerEdge R740xs 2U",
    category: "Сетевое оборудование",
    subcategory: "Роутеры",
    brand: "Dell",
    description: "Сервер 2U, 2x Xeon Silver 4210, 64 ГБ DDR4, 4x 1.2ТБ SAS, iDRAC9",
    country: "Китай",
    weightKg: 25.0,
    lengthCm: 43.5,
    widthCm: 70.0,
    heightCm: 8.7,
    color: "Чёрный",
    material: "Металл",
    model: "R740xs",
    keywords: ["сервер", "dell", "poweredge", "xeon", "2u"],
    photoUrls: ["https://img.techsupply.ru/srv-027-1.jpg"],
    equipment: "Сервер, рельсы, кабели питания, документация",
    warranty: "36 месяцев",
    ageCategory: "12+",
  },
  {
    id: 28,
    name: "Планшет Samsung Galaxy Tab A9+",
    article: "TS-TAB-028",
    exactName: "Планшет Samsung Galaxy Tab A9+ 11\" 64GB",
    category: "Электроника",
    subcategory: "Ноутбуки",
    brand: "Samsung",
    description: "Планшет 11\" TFT 90Гц, Snapdragon 695, 4/64 ГБ, Wi-Fi, стилос S Pen",
    country: "Китай",
    weightKg: 0.49,
    lengthCm: 25.7,
    widthCm: 16.4,
    heightCm: 0.7,
    color: "Серый",
    material: "Пластик / Металл",
    model: "SM-X110",
    keywords: ["планшет", "samsung", "galaxy-tab", "11дюймов", "s-pen"],
    photoUrls: ["https://img.techsupply.ru/tab-028-1.jpg"],
    equipment: "Планшет, кабель USB-C, документация",
    warranty: "12 месяцев",
    ageCategory: "6+",
  },
  {
    id: 29,
    name: "Телефон Yealink T46U",
    article: "TS-PH-029",
    exactName: "IP-телефон Yealink SIP-T46U",
    category: "Сетевое оборудование",
    subcategory: "Роутеры",
    brand: "Yealink",
    description: "IP-телефон SIP, 16 линий, цветной 4.3\" LCD, Bluetooth, Wi-Fi, PoE",
    country: "Китай",
    weightKg: 0.98,
    lengthCm: 24.0,
    widthCm: 19.5,
    heightCm: 14.5,
    color: "Чёрный",
    material: "Пластик",
    model: "SIP-T46U",
    keywords: ["телефон", "yealink", "ip", "sip", "офис"],
    photoUrls: ["https://img.techsupply.ru/ph-029-1.jpg"],
    equipment: "Телефон, трубка, кабель Ethernet, документация",
    warranty: "24 месяца",
    ageCategory: "6+",
  },
  {
    id: 30,
    name: "ИБП CyberPower CP1500PFCLCD",
    article: "TS-UPS2-030",
    exactName: "ИБП CyberPower CP1500PFCLCD PFC Sinewave 1500VA",
    category: "Офисное оборудование",
    subcategory: "ИБП",
    brand: "CyberPower",
    description: "ИБП синусоида 1500ВА/1000Вт, 10 розеток, LCD, USB, AVR, EPO",
    country: "Китай",
    weightKg: 15.0,
    lengthCm: 38.0,
    widthCm: 13.7,
    heightCm: 31.5,
    color: "Чёрный",
    material: "Пластик",
    model: "CP1500PFCLCD",
    keywords: ["ибп", "cyberpower", "ups", "1500va", "синусоида"],
    photoUrls: ["https://img.techsupply.ru/ups2-030-1.jpg"],
    equipment: "ИБП, кабель питания, документация",
    warranty: "24 месяца",
    ageCategory: "6+",
  },
]

if (process.env.NODE_ENV !== "production") {
  console.debug("[marketplace-card-fill:data] loaded", { count: MARKETPLACE_PRODUCTS.length })
}